--- 

- name: Add ppa for evernote
  apt_repository:
  sudo: yes
  args: 
    state: present
    repo: "ppa:nvbn-rm/ppa"
    update_cache: yes
  when: ansible_distribution in [ 'Ubuntu' ]

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=everpad
  when: ansible_pkg_mgr == "apt" 

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=evernote
  when: ansible_os_family == "Darwin"
  notify: linkapps
