---
- name: local.yml
  hosts: localhost
  sudo: True
  connection: local
  roles:
#    - { role: homebrew,                    tags: ["homebrew"] } #tested on mac,

#    - { role: sublime,                      tags: [ "sublime" ] }
#    - { role: java,                    		tags: [ "java" ] }
#    - { role: intellij,                   tags: [ "intellij" ] }
#    - { role: intellij,                   tags: [ "intellij" ] }
