---
- name: local.yml
  hosts: localhost
  sudo: True
  connection: local
  roles:

### mac only ###
    # - { role: homebrew,                     tags: ["homebrew"] }

### ubuntu/linuxmint only ###
#    - { role: java,                    		 tags: [ "java" ] }

### works on ubuntu/linuxmint or MacOS ###
    # - { role: sublime,                      tags: [ "sublime" ] }
#    - { role: intellij,                     tags: [ "intellij" ] }
    # - { role: pygitup,                     tags: [ "pygitup" ] } #TODO: extract role to individual repo

### works on ubuntu/linuxmint or (MacOS + homebrew + homebrew cask) ###
    - { role: wget,                     tags: [ "wget" ] }
    - { role: zsh,                      tags: [ "zsh" ] }
    - { role: zsh-completions,          tags: [ "zsh" ] }
    - { role: vagrant,                  tags: [ "vagrant" ] }
#    - { role: maven,                    tags: [ "maven" ] }
#    - { role: firefox,                  tags: [ "firefox" ] }
    - { role: gimp,                     tags: [ "gimp" ] }
    - { role: vlc,                      tags: [ "vlc" ] }
    # - { role: keepass,                  tags: [ "keepass" ] } #TODO: extract role to individual repo
#    - { role: hipchat,                  tags: [ "hipchat" ] }

# TODO
# wuala
# http://www.rainlendar.net/download/rainlendar2-lite_2.12.2.b138-1_amd64.deb
# http://www.rainlendar.net/cms/index.php?option=com_rny_download&all=1
# rainlendar: configure colours/calendars from Sparkleshare and ~/.config/.rainlendar2/rainlendar2.ini
# Sparkleshare. requirement: apt-get install mono-complete gtk-sharp3 (and others!) 
# or earlier version. manual actions: add ssh key to bitbucket etc.
# seafile
# firefox plugins: Adblock plus, jsonview
# tor
# imagemagick (apt)
# https://fix-macosx.com/fix-macosx.py 
# ssh-keygen -t rsa -b 4096
# keepass with firefox plugin: https://github.com/keithbennett/keepassx/releases/download/2.0-alpha5-kb/KeePassX-2.0-alpha5-kb.dmg
# http://spectacleapp.com/
# intellij ultimate
# gnupg
# thunderbird
# chefdk https://downloads.chef.io/chef-dk/mac/#/

### TODO:
#    - { role: git,                      tags: [ "git" ] } #settings missing
#    - { role: virtualbox,               tags: [ "virtualbox" ] } # no on mint
    # - { role: skype,                    tags: [ "skype" ] } # no on mint
