---
- name: local.yml
  hosts: localhost
  sudo: True
  connection: local
  roles:

### mac only ###
#    - { role: homebrew,                     tags: ["homebrew"] }

### ubuntu/linuxmint only ###
#    - { role: java,                    		 tags: [ "java" ] }

### works on ubuntu/linuxmint or MacOS ###
#    - { role: sublime,                      tags: [ "sublime" ] }
#    - { role: intellij,                     tags: [ "intellij" ] }
#    - { role: pygitup,                     tags: [ "pygitup" ] } #TODO: extract role to individual repo

### works on ubuntu/linuxmint or (MacOS + homebrew + homebrew cask) ###
#    - { role: wget,                     tags: [ "wget" ] }
#    - { role: zsh,                      tags: [ "zsh" ] }
#    - { role: zsh-completions,          tags: [ "zsh" ] }
#    - { role: vagrant,                  tags: [ "vagrant" ] }
#    - { role: maven,                    tags: [ "maven" ] }
#    - { role: firefox,                  tags: [ "firefox" ] }
#    - { role: gimp,                     tags: [ "gimp" ] }
#    - { role: vlc,                      tags: [ "vlc" ] }
#    - { role: keepass,                  tags: [ "keepass" ] } #TODO: extract role to individual repo

# TODO
# wuala
# http://www.rainlendar.net/download/rainlendar2-lite_2.12.2.b138-1_amd64.deb
# http://www.rainlendar.net/cms/index.php?option=com_rny_download&all=1
# Sparkleshare
# seafile
# firefox plugins
# tor
# imagemagick (apt)



### TODO:
#    - { role: git,                      tags: [ "git" ] } #settings missing
#    - { role: virtualbox,               tags: [ "virtualbox" ] } # no on mint
#    - { role: skype,                    tags: [ "skype" ] } # no on mint
