# meta file for pycharm
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up PyCharm
  license: MIT
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
      versions:
        - lucid
        - precise
        - trusty
    - name: Debian
      versions:
        - squeeze
        - wheezy
        - jessie
  categories:
    - development
    - system
dependencies: []
