---
- name: Setup homebrew install path.
  file:
    path: "{{ homebrew_install_path }}"
    group: admin
    mode: 0775
    state: directory
  sudo: yes

- name: Ensure proper permissions on /usr/local dirs.
  file:
    path: "{{ item }}"
    group: admin
    mode: 0775
    state: directory
  with_items:
    - "/usr/local"
    - "/usr/local/bin"
  sudo: yes

- name: Ensure homebrew is installed.
  git:
    repo: git://github.com/Homebrew/homebrew.git
    version: master
    dest: "{{ homebrew_install_path }}"
    update: no
    accept_hostkey: yes

- name: Check if homebrew binary is already in place.
  stat: path=/usr/local/bin/brew
  register: homebrew_binary

- name: Symlink brew to /usr/local/bin/brew.
  file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: /usr/local/bin/brew
    state: link
  when: homebrew_binary.stat.exists == false
  sudo: yes

# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: homebrew_taps

# Brew.
- name: Ensure configured homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_installed_packages

- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade_all_packages

# Cask.
- name: Get list of apps installed with cask.
  command: brew cask list
  register: homebrew_cask_list
  always_run: yes
  changed_when: false

- name: Install configured cask applications.
  command: >
    brew cask install {{ item }} --appdir={{ homebrew_cask_appdir }}
  with_items: homebrew_cask_apps
  when: "'{{ item }}' not in homebrew_cask_list.stdout"
