---

- name: Add Oracle ppa for Ubuntu
  apt_repository:
  sudo: yes
  args: 
    state: present
    repo: "ppa:webupd8team/java"
    update_cache: yes
  when: ansible_distribution in [ 'Ubuntu' ]

- name: Accept Oracle license
  debconf: name=Oracle-java7-installer question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  sudo: yes
  when: ansible_distribution in [ 'Ubuntu' ]

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=oracle-java6-installer
  when: ansible_pkg_mgr == "apt" 

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=oracle-java7-installer
  when: ansible_pkg_mgr == "apt" 

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=oracle-java7-set-default
  when: ansible_pkg_mgr == "apt" 

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=java6
  when: ansible_os_family == "Darwin"

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=java7
  when: ansible_os_family == "Darwin"

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=java
  when: ansible_os_family == "Darwin"

