---

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=zsh
  when: ansible_pkg_mgr == "apt"

- include: ../../pkg_mgr_homebrew/tasks/install_package.yml package_name=zsh
  when: ansible_os_family == "Darwin"

- name: Set zsh as default shell
  user: name={{ ansible_user_id }} shell=/bin/zsh
  sudo: yes
  when: ansible_pkg_mgr == "apt"

- name: Set zsh as default shell
  shell: chsh -s /bin/zsh
  sudo: yes
  when: ansible_os_family == "Darwin"

- name: Check oh-my-zsh is installed
  stat: path=~/.oh-my-zsh
  register: oh_my_zsh_installed

- name: Clone oh-my-zsh
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    accept_hostkey=yes
    dest=~/.oh-my-zsh
  when: oh_my_zsh_installed.stat.exists == false

- name: Replace zsh config
  copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template dest=~/.zshrc backup=yes
  when: oh_my_zsh_installed.stat.exists == false
