---

- name: Add ppa for sublime-text3
  apt_repository:
  sudo: yes
  args: 
    state: present
    repo: "ppa:webupd8team/sublime-text-3"
    update_cache: yes
  when: ansible_distribution in [ 'Ubuntu' ] and ansible_distribution_release in ['precise']

# TODO install for trusty
- name: Add ppa for sublime-text2
  apt_repository:
  sudo: yes
  args: 
    state: present
    repo: "ppa:webupd8team/sublime-text-2"
    update_cache: yes
  when: ansible_distribution in [ 'Ubuntu' ] and ansible_distribution_release in ['trusty']

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=sublime-text3
  when: ansible_pkg_mgr == "apt"  and ansible_distribution_release in ['precise']

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=sublime-text
  when: ansible_pkg_mgr == "apt"  and ansible_distribution_release in ['trusty']

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=sublime-text3
  when: ansible_os_family == "Darwin"
  notify: linkapps
