---
 - name: Ensure temp download directory exist
   file: state=directory path={{vagrant_tmp_dir}}
 - include: Debian.yml
   when: ansible_os_family == 'Debian'
 - include: RedHat.yml
   when: ansible_os_family == 'RedHat'
