---

- name: Add ppa
  apt_repository:
  sudo: yes
  args: 
    state: present
    repo:  'ppa:otto-kesselgulasch/gimp'
    update_cache: yes
  when: ansible_distribution in ['Ubuntu']

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=gimp
  when: ansible_os_family == "Darwin"
  notify: linkapps
